server.port=8081
spring.main.allow-bean-definition-overriding=true
cdn.origin-urls=https://via.placeholder.com,https://dummyimage.com
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m